# Generated by Django 3.2.5 on 2021-07-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='عنوان')),
                ('image', models.FileField(blank=True, null=True, upload_to='Services/', verbose_name='عکس')),
            ],
            options={
                'verbose_name': 'خدمات',
                'verbose_name_plural': 'ماژول خدمات',
            },
        ),
    ]
