# Generated by Django 3.2.5 on 2021-07-31 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='url',
            field=models.CharField(max_length=100, null=True, verbose_name='آدرس'),
        ),
    ]
