# Generated by Django 3.2.4 on 2021-06-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(max_length=1000, verbose_name='توضیحات')),
                ('image', models.FileField(blank=True, null=True, upload_to='Articles/', verbose_name='تصاویر')),
                ('active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
    ]
