# Generated by Django 3.2.5 on 2021-07-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0002_alter_category_options'),
        ('articles', '0002_article_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(blank=True, to='Category.Category', verbose_name='دسته بندی ها'),
        ),
    ]
