# Generated by Django 3.2.5 on 2021-07-21 11:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000000, null=True, verbose_name='توضیحات'),
        ),
    ]
