# Generated by Django 3.2.5 on 2021-07-22 12:59

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_article_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2021, 7, 22)),
        ),
    ]
