# Generated by Django 3.2.5 on 2021-07-23 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0025_alter_article_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='date',
        ),
    ]
