# Generated by Django 3.2.5 on 2021-07-23 10:57

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0026_remove_article_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date',
            field=django_jalali.db.models.jDateField(null=True, verbose_name='تاریخ'),
        ),
    ]
