# Generated by Django 3.2.5 on 2021-07-23 11:02

import datetime
from django.db import migrations
from django.utils.timezone import utc
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0028_alter_article_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=django_jalali.db.models.jDateTimeField(null=True, verbose_name=datetime.datetime(2021, 7, 23, 11, 2, 30, 362244, tzinfo=utc)),
        ),
    ]
