# Generated by Django 3.2.5 on 2021-07-23 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0035_remove_article_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='active',
        ),
        migrations.RemoveField(
            model_name='article',
            name='featured',
        ),
    ]
