# Generated by Django 3.2.5 on 2021-07-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0004_remove_category_image'),
        ('gallery', '0002_alter_gallery_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='categories',
            field=models.ManyToManyField(blank=True, to='Category.Category', verbose_name='دسته بندی ها'),
        ),
    ]
