# Generated by Django 3.2.5 on 2021-07-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=128, verbose_name='نام و نام خانوادگی')),
                ('Phone', models.CharField(max_length=128, verbose_name='تلفن')),
                ('Text', models.TextField(max_length=10000, verbose_name='متن پیام')),
            ],
        ),
    ]
