# Generated by Django 3.2.5 on 2021-07-31 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_dr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about_dr',
            options={'verbose_name': 'درباره دکتر', 'verbose_name_plural': 'ماژول درباره دکتر'},
        ),
    ]
