# Generated by Django 3.2.5 on 2021-08-03 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_dr', '0002_alter_about_dr_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about_dr',
            options={'verbose_name': 'درباره دکتر', 'verbose_name_plural': 'درباره دکتر'},
        ),
    ]
