# Generated by Django 3.2.5 on 2021-07-11 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0003_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
