# Generated by Django 3.2.5 on 2021-07-18 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Banner',
            new_name='LavinBanner',
        ),
    ]
